// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ConversationType string

const (
	ConversationTypeDirect ConversationType = "direct"
	ConversationTypeGroup  ConversationType = "group"
)

func (e *ConversationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationType(s)
	case string:
		*e = ConversationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationType: %T", src)
	}
	return nil
}

type NullConversationType struct {
	ConversationType ConversationType
	Valid            bool // Valid is true if ConversationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationType) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationType), nil
}

type Conversation struct {
	ID        uuid.UUID
	Type      ConversationType
	CreatedAt time.Time
}

type ConversationMember struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
	JoinedAt       time.Time
}

type FriendRequest struct {
	RequesterID uuid.UUID
	TargetID    uuid.UUID
	CreatedAt   time.Time
}

type Friendship struct {
	UserID    uuid.UUID
	FriendID  uuid.UUID
	CreatedAt time.Time
}

type Match struct {
	ID                uuid.UUID
	WhiteID           uuid.UUID
	BlackID           uuid.UUID
	TimeControl       string
	WhiteRatingBefore int32
	BlackRatingBefore int32
	WhiteRatingAfter  int32
	BlackRatingAfter  int32
	Result            string
	CreatedAt         time.Time
	FinishedAt        sql.NullTime
}

type MatchMove struct {
	ID          int64
	MatchID     uuid.UUID
	MoveNumber  int32
	PlayerID    uuid.UUID
	San         string
	Uci         string
	FenAfter    string
	WhiteTimeMs int64
	BlackTimeMs int64
	CreatedAt   time.Time
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Content        string
	CreatedAt      time.Time
	EditedAt       sql.NullTime
	DeletedAt      sql.NullTime
}

type Rating struct {
	UserID      uuid.UUID
	RatingType  string
	Rating      int32
	GamesPlayed int32
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	UserAgent        sql.NullString
	IpAddress        sql.NullString
	CreatedAt        time.Time
	ExpiresAt        time.Time
	MaxExpiresAt     time.Time
	LastUsedAt       sql.NullTime
	RevokedAt        sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
