// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type FriendRequest struct {
	RequesterID uuid.UUID
	TargetID    uuid.UUID
	CreatedAt   time.Time
}

type Friendship struct {
	UserID    uuid.UUID
	FriendID  uuid.UUID
	CreatedAt time.Time
}

type Match struct {
	ID                uuid.UUID
	WhiteID           uuid.UUID
	BlackID           uuid.UUID
	TimeControl       string
	WhiteRatingBefore int32
	BlackRatingBefore int32
	WhiteRatingAfter  int32
	BlackRatingAfter  int32
	Result            string
	CreatedAt         time.Time
	FinishedAt        sql.NullTime
}

type MatchMove struct {
	ID          int64
	MatchID     uuid.UUID
	MoveNumber  uuid.UUID
	PlayerID    uuid.UUID
	San         string
	Uci         string
	FenAfter    string
	WhiteTimeMs int64
	BlackTimeMs int64
	CreatedAt   time.Time
}

type Rating struct {
	UserID      uuid.UUID
	RatingType  string
	Rating      int32
	GamesPlayed int32
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	UserAgent        sql.NullString
	IpAddress        sql.NullString
	CreatedAt        time.Time
	ExpiresAt        time.Time
	MaxExpiresAt     time.Time
	LastUsedAt       sql.NullTime
	RevokedAt        sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
